### ISSUE TITLE
[DOC] liberty installation instructions

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-openstack-heat-plugins#114]
Hi

If I install liberty packages of LBaaS, in short installing the following packages

```
root@dc8-1f-66-b8-bd-ca:~ # ls -l *.rpm
-rw-r--r-- 1 root root  15528 Aug  3 14:50 f5-icontrol-rest-1.0.9-1.el7.noarch.rpm
-rw-r--r-- 1 root root 172680 Oct 10 14:49 f5-openstack-agent-8.1.0-1.el7.noarch.rpm
-rw-r--r-- 1 root root  47316 Oct 11 10:44 f5-openstack-lbaasv2-driver-8.1.0-1.el7.noarch.rpm
-rw-r--r-- 1 root root 168428 Sep 27 14:16 f5-sdk-1.5.0-1.el7.noarch.rpm

```
and then I try to install the Heat plugin using the liberty's instructions

`pip install f5-openstack-heat-plugins
`

It does install the latest version rather than the supported version indicated in the web page:

http://f5-openstack-heat-plugins.readthedocs.io/en/liberty/

Indeed it does uninstall the previously f5-sdk package:
```

root@dc8-1f-66-b8-bd-ca:~ # pip install f5-openstack-heat-plugins
Downloading/unpacking f5-openstack-heat-plugins
  Downloading f5-openstack-heat-plugins-9.0.2.tar.gz
  Running setup.py egg_info for package f5-openstack-heat-plugins
    
Downloading/unpacking f5-sdk==1.0.0 (from f5-openstack-heat-plugins)
  Downloading f5-sdk-1.0.0.tar.gz (62kB): 62kB downloaded
  Running setup.py egg_info for package f5-sdk
    
    warning: no files found matching 'README.md'
    warning: no files found matching 'SUPPORT'
Requirement already satisfied (use --upgrade to upgrade): f5-icontrol-rest>=1.0.7 in /usr/lib/python2.7/site-packages (from f5-sdk==1.0.0->f5-openstack-heat-plugins)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.5.0 in /usr/lib/python2.7/site-packages (from f5-icontrol-rest>=1.0.7->f5-sdk==1.0.0->f5-openstack-heat-plugins)
Installing collected packages: f5-openstack-heat-plugins, f5-sdk
  Running setup.py install for f5-openstack-heat-plugins
    
  Found existing installation: f5-sdk 1.5.0
    Uninstalling f5-sdk:
      Successfully uninstalled f5-sdk
  Running setup.py install for f5-sdk
    
    warning: no files found matching 'README.md'
    warning: no files found matching 'SUPPORT'
Successfully installed f5-openstack-heat-plugins f5-sdk
Cleaning up...

```

**Comment by alonsocamaro** [comment]
I think it should be the following command but I get an error

```
root@dc8-1f-66-b8-bd-ca:~ # pip install git+https://github.com/F5Networks/f5-openstack-heat@liberty
Downloading/unpacking git+https://github.com/F5Networks/f5-openstack-heat@liberty
  Cloning https://github.com/F5Networks/f5-openstack-heat (to liberty) to /tmp/pip-2c4NxQ-build
  Running setup.py egg_info for package from git+https://github.com/F5Networks/f5-openstack-heat@liberty
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-2c4NxQ-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-2c4NxQ-build/setup.py'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-2c4NxQ-build
Storing complete log in /root/.pip/pip.log

```

**Comment by pjbreaux** [comment]
@alonsocamaro: You can do pip install f5-openstack-heat-plugins==8.0.3, which will give you the exact version of the liberty release. I get the same failure doing the pip install from github directly. This is a valid issue.

**Comment by alonsocamaro** [comment]
Yep, it did work but I find that it uninstalls the sdk version necessary for LBaaSv2

```
root@dc8-1f-66-b8-bd-ca:~ # pip install f5-openstack-heat-plugins==8.0.3
Downloading/unpacking f5-openstack-heat-plugins==8.0.3
  Downloading f5-openstack-heat-plugins-8.0.3.tar.gz
  Running setup.py egg_info for package f5-openstack-heat-plugins

Downloading/unpacking f5-sdk==1.0.0 (from f5-openstack-heat-plugins==8.0.3)
  Downloading f5-sdk-1.0.0.tar.gz (62kB): 62kB downloaded
  Running setup.py egg_info for package f5-sdk

    warning: no files found matching 'README.md'
    warning: no files found matching 'SUPPORT'
Requirement already satisfied (use --upgrade to upgrade): f5-icontrol-rest>=1.0.7 in /usr/lib/python2.7/site-packages (from f5-sdk==1.0.0->f5-openstack-heat-plugins==8.0.3)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.5.0 in /usr/lib/python2.7/site-packages (from f5-icontrol-rest>=1.0.7->f5-sdk==1.0.0->f5-openstack-heat-plugins==8.0.3)
Installing collected packages: f5-openstack-heat-plugins, f5-sdk
  Running setup.py install for f5-openstack-heat-plugins

  Found existing installation: f5-sdk 1.5.0
    Uninstalling f5-sdk:
      Successfully uninstalled f5-sdk
  Running setup.py install for f5-sdk

    warning: no files found matching 'README.md'
    warning: no files found matching 'SUPPORT'
Successfully installed f5-openstack-heat-plugins f5-sdk
Cleaning up...

```

**Comment by pjbreaux** [comment]
Yes, we can't guarantee that they aren't mutually exclusive.

**Comment by alonsocamaro** [comment]
This is not good for the customers...

... and is 1.5.0 backwards compatible with 1.0.0? If it is compatible it would be just about adjusting the dependencies in the pip install

**Comment by pjbreaux** [comment]
Yes 1.5 should be backwards compatible with 1.0.0. We'll talk about supporting this and see where we get.

**Comment by alonsocamaro** [comment]
Would you say that as a workaround the following is acceptable?
- pip install f5-heat
- pip uninstall f5-sdk
- install lbaasv2 all components (which includes f5-sdk 1.5.0)

**Comment by pjbreaux** [comment]
That is untested by us, but it looks sound.

**Comment by alonsocamaro** [comment]
Hi again Paul

Additionally... could this issue be also tagged as a documentation bug too?

I think that all pip install commands shown should explicitly indicate the version to install.

Otherwise users might unexpectedly install a different version (the latest). Could this be a policy in our installation instructions for any "pip install" ?

So in summary I think this bug should cover two things:

- pip install with implicit version specified in the documentation
- heat-plugins and lbaas compatibility for a given release of these. Ideally a compatibility table too.

Thanks
