### ISSUE TITLE
LTM Pool resource does not skip adding members if no members are present in heat template

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-heat-plugins#13]
This bug is hit when a heat stack is launch that does not assigned any members to a pool. The error is:

2016-03-11 08:56:13.160 56129 INFO heat.engine.resource [-] CREATE: F5LTMPool "ve_pool" Stack "test" [a3f774fa-d61c-4367-87a6-31ec56ac7726]
2016-03-11 08:56:13.160 56129 TRACE heat.engine.resource Traceback (most recent call last):
2016-03-11 08:56:13.160 56129 TRACE heat.engine.resource   File "/usr/lib/python2.7/site-packages/heat/engine/resource.py", line 500, in _action_recorder
2016-03-11 08:56:13.160 56129 TRACE heat.engine.resource     yield
2016-03-11 08:56:13.160 56129 TRACE heat.engine.resource   File "/usr/lib/python2.7/site-packages/heat/engine/resource.py", line 570, in _do_action
2016-03-11 08:56:13.160 56129 TRACE heat.engine.resource     yield self.action_handler_task(action, args=handler_args)
2016-03-11 08:56:13.160 56129 TRACE heat.engine.resource   File "/usr/lib/python2.7/site-packages/heat/engine/scheduler.py", line 296, in wrapper
2016-03-11 08:56:13.160 56129 TRACE heat.engine.resource     step = next(subtask)
2016-03-11 08:56:13.160 56129 TRACE heat.engine.resource   File "/usr/lib/python2.7/site-packages/heat/engine/resource.py", line 541, in action_handler_task
2016-03-11 08:56:13.160 56129 TRACE heat.engine.resource     handler_data = handler(*args)
2016-03-11 08:56:13.160 56129 TRACE heat.engine.resource   File "/usr/lib/python2.7/site-packages/f5_heat/resources/common/mixins.py", line 21, in func_wrapper
2016-03-11 08:56:13.160 56129 TRACE heat.engine.resource   File "/usr/lib/python2.7/site-packages/f5_heat/resources/f5_ltm_pool.py", line 133, in handle_create
2016-03-11 08:56:13.160 56129 TRACE heat.engine.resource   File "/usr/lib/python2.7/site-packages/f5_heat/resources/f5_ltm_pool.py", line 96, in _assign_members
2016-03-11 08:56:13.160 56129 TRACE heat.engine.resource TypeError: 'NoneType' object is not iterable

A check is needed to determine whether to try and assign members at all based on whether any members were set in the yaml file.

**Comment by pjbreaux** [comment]
Closed by PR #14
